version: '3.8'

services:
  # db:
  #   image: mysql:5.7.44
  #   command: --init-file /var/lib/docker/volumes/db/init.sql --innodb-use-native-aio=0 --explicit_defaults_for_timestamp=false
  #   volumes:
  #     - ./db:/var/lib/docker/volumes/db
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: test
  #     MYSQL_DATABASE: test
  #     MYSQL_USER: test
  #     MYSQL_PASSWORD: test
  #     MYSQL_ROOT_HOST: '%'
  #   ports:
  #     - 3306:3306

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8081:8080
  #   depends_on:
  #     - db

  node_app:
    container_name: my_node
    image: node:18.18.0-alpine
    restart: always
    working_dir: /home/node/mvc_node_express
    volumes:
      - ./:/home/node/mvc_node_express
    command: sh -c "npm install -g nodemon && npm install && npm run dev"
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    # depends_on:
    #   - db
